#---------------------------
# 关于页
# About Page
#---------------------------
about:
  enable: true
  banner_img: /img/backend.png
  banner_img_height: 60
  banner_mask_alpha: 0.3
  avatar: /img/touxiang.png
  name: "Reigie"
  intro: "一起探索Spring React"
  # 更多图标可从 https://hexo.fluid-dev.com/docs/icon/ 查找，`class` 代表图标的 css class，添加 `qrcode` 后，图标不再是链接而是悬浮二维码
  # More icons can be found from https://hexo.fluid-dev.com/docs/en/icon/  `class` is the css class of the icon. If adding `qrcode`, The icon is no longer a link, but a hovering QR code
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/Reigie", tip: "GitHub" }
    - { class: "iconfont icon-bilibili-fill", link: "https://space.bilibili.com/86058502?spm_id_from=333.1007.0.0", tip: "b站" }
    - { class: "iconfont icon-wechat-fill", qrcode: "/img/wechatQR.png" }
